### ISSUE TITLE
Undefined variable: object

### ISSUE THREAD

**Issue by dhb1989** [JDpawar/yii2_aws_s3#1]
Hello,

I have installed this sdk properly and also follow steps to configuration but its getting error, "Undefined variable: object" on controller file. you can check screenshot, http://s22.postimg.org/c9kr9eve9/screenshot.jpg

Can you please help me on this?

Thanks

**Comment by JDpawar** [comment]
@dhb1989 
You will have to create a new object of the class AwsS3 before using any function

```
$object = new AwsS3();
$object->uploadObject(...)
```

**Comment by dhb1989** [comment]
Thanks JDpawar for reply me,

I have added object class and now getting other error, "Class 'app\controllers\AwsS3' not found"

**Comment by JDpawar** [comment]
@dhb1989 
Can you show the code of the following files
config/main.php
AwsS3.php - class

**Comment by dhb1989** [comment]
@JDpawar 
Sure, but i'm using Yii2.0.9 so, there is not main.php inside the config folder and where can i find out AwsS3.php class file?

**Comment by JDpawar** [comment]
@dhb1989 
Possible for you to add me to your repo?
I'll check the code.

**Comment by dhb1989** [comment]
but my code is not on repo, run app from local machine

**Comment by dhb1989** [comment]
can we connect via teamviewer?

**Comment by JDpawar** [comment]
Sure!
Mail me on jaydeep1012@gmail.com

**Comment by dhb1989** [comment]
okay, thanks
